using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PlaygroundProgram.Customers
{
    public class CustomerRepository
    {
        public static List<Customer> LoadCustomers()
        {
            var customers = new List<Customer>
            {
                new Customer
                {
                    Id = 1,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Louise",
                    MiddleInitial = "C",
                    Surname = "Midgett",
                    Address = new Address
                    {
                        StreetAddress = "43 Compare Valley",
                        City = "Chambersburg",
                        State = "PA",
                        ZipCode = 17201,
                        Country = "US",
                    },
                    EmailAddress = "LouiseCMidgett@dodgit.com",
                    TelephoneNumber = "717-261-7855",
                    MothersMaiden = "Kelly",
                    NextBirthday = Convert.ToDateTime("1-May-84"),
                    CCType = "Visa",
                    CaseFileID = "192-80-6448",
                    UPS = "1Z W64 924 70 0191 812 7",
                    Occupation = "Traffic technician",
                    Domain = "ScottsdaleSkincare.com",
                    MembershipLevel = "A+",
                    Kilograms = "64.2",
                },
                new Customer
                {
                    Id = 2,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Shirley",
                    MiddleInitial = "H",
                    Surname = "Lewis",
                    Address = new Address
                    {
                        StreetAddress = "4612 Lakewood Drive",
                        City = "Rochelle Park",
                        State = "NJ",
                        ZipCode = 7662,
                        Country = "US",
                    },
                    EmailAddress = "ShirleyHLewis@spambob.com",
                    TelephoneNumber = "201-881-8239",
                    MothersMaiden = "Mullins",
                    NextBirthday = Convert.ToDateTime("2-Jun-73"),
                    CCType = "MasterCard",
                    CaseFileID = "147-01-3534",
                    UPS = "1Z V21 901 02 8740 039 4",
                    Occupation = "Dermatologist",
                    Domain = "BuyingTVs.com",
                    MembershipLevel = "A+",
                    Kilograms = "104.7",
                },
                new Customer
                {
                    Id = 3,
                    Gender = Gender.Male,
                    FirstName = "Wayne",
                    MiddleInitial = "V",
                    Surname = "Campbell",
                    Address = new Address
                    {
                        StreetAddress = "2493 Chapmans Lane",
                        City = "Albuquerque",
                        State = "NM",
                        ZipCode = 87109,
                        Country = "US",
                    },
                    EmailAddress = "WayneVCampbell@pookmail.com",
                    TelephoneNumber = "505-823-9031",
                    MothersMaiden = "Robertson",
                    NextBirthday = Convert.ToDateTime("10-Oct-69"),
                    CCType = "Visa",
                    CaseFileID = "649-24-0920",
                    UPS = "1Z 665 4Y4 65 4781 199 6",
                    Occupation = "Lobby attendant",
                    Domain = "DigitClub.com",
                    MembershipLevel = "A+",
                    Kilograms = "64.1",
                },
                new Customer
                {
                    Id = 4,
                    Gender = Gender.Male,
                    FirstName = "Ben",
                    MiddleInitial = "E",
                    Surname = "Cribbs",
                    Address = new Address
                    {
                        StreetAddress = "4652 Sardis Sta",
                        City = "Chicago",
                        State = "IL",
                        ZipCode = 76020,
                        Country = "US",
                    },
                    EmailAddress = "BenECribbs@pookmail.com",
                    TelephoneNumber = "817-677-2247",
                    MothersMaiden = "Prestridge",
                    NextBirthday = Convert.ToDateTime("5-Dec-73"),
                    CCType = "MasterCard",
                    CaseFileID = "449-11-2576",
                    UPS = "1Z 5A4 659 77 2176 039 5",
                    Occupation = "Clinical laboratory technician",
                    Domain = "BetLimit.com",
                    MembershipLevel = "A+",
                    Kilograms = "85.5",
                },
                new Customer
                {
                    Id = 5,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Roberta",
                    MiddleInitial = "M",
                    Surname = "Deputy",
                    Address = new Address
                    {
                        StreetAddress = "3409 Water Street",
                        City = "Concord",
                        State = "CA",
                        ZipCode = 94520,
                        Country = "US",
                    },
                    EmailAddress = "RobertaMDeputy@pookmail.com",
                    TelephoneNumber = "925-353-5110",
                    MothersMaiden = "Denny",
                    NextBirthday = Convert.ToDateTime("20-Oct-92"),
                    CCType = "MasterCard",
                    CaseFileID = "623-90-2881",
                    UPS = "1Z 412 811 93 0188 217 0",
                    Occupation = "Lease operator",
                    Domain = "RentalFest.com",
                    MembershipLevel = "O+",
                    Kilograms = "51",
                },
                new Customer
                {
                    Id = 6,
                    Gender = Gender.Male,
                    FirstName = "Clarence",
                    MiddleInitial = "C",
                    Surname = "Huynh",
                    Address = new Address
                    {
                        StreetAddress = "2324 Gateway Avenue",
                        City = "Bakersfield",
                        State = "CA",
                        ZipCode = 93301,
                        Country = "US",
                    },
                    EmailAddress = "ClarenceCHuynh@dodgit.com",
                    TelephoneNumber = "661-864-5545",
                    MothersMaiden = "Hanks",
                    NextBirthday = Convert.ToDateTime("15-Dec-54"),
                    CCType = "MasterCard",
                    CaseFileID = "561-48-7309",
                    UPS = "1Z 722 A53 43 9718 870 7",
                    Occupation = "Portrait photographer",
                    Domain = "OpenAdvertiser.com",
                    MembershipLevel = "O+",
                    Kilograms = "102.1",
                },
                new Customer
                {
                    Id = 7,
                    Gender = Gender.Male,
                    FirstName = "Jose",
                    MiddleInitial = "T",
                    Surname = "Duke",
                    Address = new Address
                    {
                        StreetAddress = "4312 Laurel Lane",
                        City = "Hobbs",
                        State = "TX",
                        ZipCode = 88240,
                        Country = "US",
                    },
                    EmailAddress = "JoseTDuke@dodgit.com",
                    TelephoneNumber = "432-297-7331",
                    MothersMaiden = "Roberson",
                    NextBirthday = Convert.ToDateTime("11-May-35"),
                    CCType = "Visa",
                    CaseFileID = "450-79-7632",
                    UPS = "1Z 904 901 95 9296 591 7",
                    Occupation = "Employment coordinator",
                    Domain = "LodgingShop.com",
                    MembershipLevel = "B+",
                    Kilograms = "92.4",
                },
                new Customer
                {
                    Id = 8,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Martha",
                    MiddleInitial = "S",
                    Surname = "Redmond",
                    Address = new Address
                    {
                        StreetAddress = "2130 Eagle Lane",
                        City = "Duluth",
                        State = "MN",
                        ZipCode = 55805,
                        Country = "US",
                    },
                    EmailAddress = "MarthaSRedmond@trashymail.com",
                    TelephoneNumber = "218-728-9438",
                    MothersMaiden = "Howard",
                    NextBirthday = Convert.ToDateTime("28-Aug-82"),
                    CCType = "MasterCard",
                    CaseFileID = "477-27-4498",
                    UPS = "1Z W85 6V7 27 1920 438 9",
                    Occupation = "Real property assessor",
                    Domain = "ParkingAlternatives.com",
                    MembershipLevel = "AB+",
                    Kilograms = "71.2",
                },
                new Customer
                {
                    Id = 9,
                    Gender = Gender.Male,
                    FirstName = "Virgil",
                    MiddleInitial = "T",
                    Surname = "Thomas",
                    Address = new Address
                    {
                        StreetAddress = "581 Rogers Street",
                        City = "Cincinnati",
                        State = "OH",
                        ZipCode = 45227,
                        Country = "US",
                    },
                    EmailAddress = "VirgilTThomas@pookmail.com",
                    TelephoneNumber = "513-527-8842",
                    MothersMaiden = "Chavez",
                    NextBirthday = Convert.ToDateTime("25-May-47"),
                    CCType = "Visa",
                    CaseFileID = "279-60-1013",
                    UPS = "1Z 602 646 62 4308 463 1",
                    Occupation = "Smoke jumper",
                    Domain = "DataFormula.com",
                    MembershipLevel = "B+",
                    Kilograms = "93.3",
                },
                new Customer
                {
                    Id = 10,
                    Gender = Gender.Male,
                    FirstName = "Robert",
                    MiddleInitial = "E",
                    Surname = "Enlow",
                    Address = new Address
                    {
                        StreetAddress = "948 Quilly Lane",
                        City = "Columbus",
                        State = "OH",
                        ZipCode = 43085,
                        Country = "US"
                    },
                    EmailAddress = "RobertEEnlow@dodgit.com",
                    TelephoneNumber = "614-589-7680",
                    MothersMaiden = "Sprague",
                    NextBirthday = Convert.ToDateTime("15-May-76"),
                    CCType = "MasterCard",
                    CaseFileID = "280-32-8000",
                    UPS = "1Z 00F 438 83 0274 708 4",
                    Occupation = "Manifold binding worker",
                    Domain = "RemoteShack.com",
                    MembershipLevel = "O+",
                    Kilograms = "78.5",
                },
                new Customer
                {
                    Id = 11,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Maria",
                    MiddleInitial = "M",
                    Surname = "Jones",
                    Address = new Address
                    {
                        StreetAddress = "3435 Jewell Road",
                        City = "Minneapolis",
                        State = "MN",
                        ZipCode = 55402,
                        Country = "US",
                    },
                    EmailAddress = "MariaMJones@pookmail.com",
                    TelephoneNumber = "612-625-9345",
                    MothersMaiden = "Taylor",
                    NextBirthday = Convert.ToDateTime("16-Jan-83"),
                    CCType = "Visa",
                    CaseFileID = "477-36-6680",
                    UPS = "1Z 462 160 03 3492 073 6",
                    Occupation = "English to speakers of other languages teacher",
                    Domain = "GadgetRewards.com",
                    MembershipLevel = "O+",
                    Kilograms = "84.1",
                },
                new Customer
                {
                    Id = 12,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Lisha",
                    MiddleInitial = "T",
                    Surname = "Perkins",
                    Address = new Address
                    {
                        StreetAddress = "307 Davis Place",
                        City = "Margaretta (Township)",
                        State = "OH",
                        ZipCode = 44824,
                        Country = "US",
                    },
                    EmailAddress = "LishaTPerkins@mailinator.com",
                    TelephoneNumber = "419-271-0942",
                    MothersMaiden = "Walker",
                    NextBirthday = Convert.ToDateTime("2-Jul-84"),
                    CCType = "MasterCard",
                    CaseFileID = "274-60-3356",
                    UPS = "1Z 286 293 53 1920 213 4",
                    Occupation = "Conservation forester",
                    Domain = "TapCredit.com",
                    MembershipLevel = "O+",
                    Kilograms = "71.8",
                },
                new Customer
                {
                    Id = 13,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Geraldine",
                    MiddleInitial = "S",
                    Surname = "Yazzie",
                    Address = new Address
                    {
                        StreetAddress = "4401 New Creek Road",
                        City = "Huntsville",
                        State = "AL",
                        ZipCode = 35806,
                        Country = "US",
                    },
                    EmailAddress = "GeraldineSYazzie@mailinator.com",
                    TelephoneNumber = "256-964-1244",
                    MothersMaiden = "Lewis",
                    NextBirthday = Convert.ToDateTime("25-Jul-75"),
                    CCType = "Visa",
                    CaseFileID = "419-34-9861",
                    UPS = "1Z 193 153 03 9044 329 9",
                    Occupation = "Neuropsychologist",
                    Domain = "DiscTower.com",
                    MembershipLevel = "O+",
                    Kilograms = "50.3",
                },
                new Customer
                {
                    Id = 14,
                    Gender = Gender.Male,
                    FirstName = "Erik",
                    MiddleInitial = "A",
                    Surname = "Salinas",
                    Address = new Address
                    {
                        StreetAddress = "3751 Chatham Way",
                        City = "Mc Lean",
                        State = "MD",
                        ZipCode = 22102,
                        Country = "US",
                    },
                    EmailAddress = "ErikASalinas@spambob.com",
                    TelephoneNumber = "240-516-4199",
                    MothersMaiden = "Taylor",
                    NextBirthday = Convert.ToDateTime("17-Nov-61"),
                    CCType = "MasterCard",
                    CaseFileID = "214-20-8869",
                    UPS = "1Z 446 1W1 18 8059 088 7",
                    Occupation = "Footwear and accessory designer",
                    Domain = "CareerMilestone.com",
                    MembershipLevel = "O+",
                    Kilograms = "90.2",
                },
                new Customer
                {
                    Id = 15,
                    Gender = Gender.Male,
                    FirstName = "Jorge",
                    MiddleInitial = "M",
                    Surname = "Brooks",
                    Address = new Address
                    {
                        StreetAddress = "2327 Mill Street",
                        City = "Anderson",
                        State = "SC",
                        ZipCode = 29621,
                        Country = "US",
                    },
                    EmailAddress = "JorgeMBrooks@pookmail.com",
                    TelephoneNumber = "864-224-4369",
                    MothersMaiden = "Swanson",
                    NextBirthday = Convert.ToDateTime("14-May-47"),
                    CCType = "MasterCard",
                    CaseFileID = "656-03-9151",
                    UPS = "1Z W03 629 57 3072 231 4",
                    Occupation = "Loan closer",
                    Domain = "BBQPage.com",
                    MembershipLevel = "B+",
                    Kilograms = "103.6",
                },
                new Customer
                {
                    Id = 16,
                    Gender = Gender.Male,
                    FirstName = "Daniel",
                    MiddleInitial = "J",
                    Surname = "Palen",
                    Address = new Address
                    {
                        StreetAddress = "1876 Amethyst Drive",
                        City = "Lansing",
                        State = "MI",
                        ZipCode = 48933,
                        Country = "US",
                    },
                    EmailAddress = "DanielJPalen@pookmail.com",
                    TelephoneNumber = "517-374-2388",
                    MothersMaiden = "Bryan",
                    NextBirthday = Convert.ToDateTime("14-Jun-73"),
                    CCType = "Visa",
                    CaseFileID = "383-58-9342",
                    UPS = "1Z 983 870 47 2361 324 7",
                    Occupation = "Sales worker",
                    Domain = "AMRegister.com",
                    MembershipLevel = "B+",
                    Kilograms = "73.1",
                },
                new Customer
                {
                    Id = 17,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Joyce",
                    MiddleInitial = "R",
                    Surname = "Walls",
                    Address = new Address
                    {
                        StreetAddress = "1384 Shinn Avenue",
                        City = "Jeannette",
                        State = "PA",
                        ZipCode = 15644,
                        Country = "US",
                    },
                    EmailAddress = "JoyceRWalls@pookmail.com",
                    TelephoneNumber = "724-523-2446",
                    MothersMaiden = "Hart",
                    NextBirthday = Convert.ToDateTime("19-Mar-75"),
                    CCType = "MasterCard",
                    CaseFileID = "159-10-6233",
                    UPS = "1Z 688 017 56 5214 016 9",
                    Occupation = "Furnace kiln oven drier and kettle operator",
                    Domain = "AudioFail.com",
                    MembershipLevel = "A+",
                    Kilograms = "104.5",
                },
                new Customer
                {
                    Id = 18,
                    Gender = Gender.Male,
                    FirstName = "Darren",
                    MiddleInitial = "C",
                    Surname = "Burkholder",
                    Address = new Address
                    {
                        StreetAddress = "3435 Oliverio Drive",
                        City = "Ellinwood",
                        State = "KS",
                        ZipCode = 67526,
                        Country = "US",
                    },
                    EmailAddress = "DarrenCBurkholder@dodgit.com",
                    TelephoneNumber = "620-564-4034",
                    MothersMaiden = "Evans",
                    NextBirthday = Convert.ToDateTime("18-Jun-69"),
                    CCType = "Visa",
                    CaseFileID = "510-19-6781",
                    UPS = "1Z W14 A21 85 8802 236 1",
                    Occupation = "Layout artist",
                    Domain = "SeeMembers.com",
                    MembershipLevel = "O+",
                    Kilograms = "99.9",
                },
                new Customer
                {
                    Id = 19,
                    Gender = Gender.Male,
                    FirstName = "Stephen",
                    MiddleInitial = "E",
                    Surname = "Woodall",
                    Address = new Address
                    {
                        StreetAddress = "3090 Rivendell Drive",
                        City = "Youngstown",
                        State = "OH",
                        ZipCode = 44503,
                        Country = "US",
                    },
                    EmailAddress = "StephenEWoodall@spambob.com",
                    TelephoneNumber = "330-817-1082",
                    MothersMaiden = "Brooks",
                    NextBirthday = Convert.ToDateTime("17-Oct-78"),
                    CCType = "MasterCard",
                    CaseFileID = "268-22-2576",
                    UPS = "1Z 254 410 87 6251 255 2",
                    Occupation = "Keying machine operator",
                    Domain = "DemocraticUpdate.com",
                    MembershipLevel = "O+",
                    Kilograms = "71.4",
                },
                new Customer
                {
                    Id = 20,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Carla",
                    MiddleInitial = "F",
                    Surname = "Light",
                    Address = new Address
                    {
                        StreetAddress = "403 Brookside Drive",
                        City = "York",
                        State = "AL",
                        ZipCode = 36925,
                        Country = "US",
                    },
                    EmailAddress = "CarlaFLight@trashymail.com",
                    TelephoneNumber = "205-392-9167",
                    MothersMaiden = "Garza",
                    NextBirthday = Convert.ToDateTime("19-May-90"),
                    CCType = "Visa",
                    CaseFileID = "421-86-3635",
                    UPS = "1Z 8W8 4V7 77 4384 400 8",
                    Occupation = "Voice writer",
                    Domain = "MagicWines.com",
                    MembershipLevel = "O+",
                    Kilograms = "65.8",
                },
                new Customer
                {
                    Id = 21,
                    Gender = Gender.Male,
                    FirstName = "Michael",
                    MiddleInitial = "E",
                    Surname = "Ford",
                    Address = new Address
                    {
                        StreetAddress = "1937 Burnside Avenue",
                        City = "Nephi",
                        State = "UT",
                        ZipCode = 84648,
                        Country = "US",
                    },
                    EmailAddress = "MichaelEFord@pookmail.com",
                    TelephoneNumber = "435-623-8423",
                    MothersMaiden = "Bratton",
                    NextBirthday = Convert.ToDateTime("8-Sep-44"),
                    CCType = "MasterCard",
                    CaseFileID = "647-14-8828",
                    UPS = "1Z 904 443 44 1352 529 8",
                    Occupation = "Mental health counselor",
                    Domain = "AreaVoip.com",
                    MembershipLevel = "A+",
                    Kilograms = "77.8",
                },
                new Customer
                {
                    Id = 22,
                    Gender = Gender.Male,
                    FirstName = "Russell",
                    MiddleInitial = "D",
                    Surname = "Acord",
                    Address = new Address
                    {
                        StreetAddress = "2535 Argonne Street",
                        City = "Philadelphia",
                        State = "DE",
                        ZipCode = 19103,
                        Country = "US",
                    },
                    EmailAddress = "RussellDAcord@trashymail.com",
                    TelephoneNumber = "302-252-7912",
                    MothersMaiden = "Olson",
                    NextBirthday = Convert.ToDateTime("24-Sep-76"),
                    CCType = "MasterCard",
                    CaseFileID = "221-24-8046",
                    UPS = "1Z 244 439 77 6365 598 1",
                    Occupation = "Bookbinder",
                    Domain = "PimpTShirt.com",
                    MembershipLevel = "O+",
                    Kilograms = "112.8",
                },
                new Customer
                {
                    Id = 23,
                    Gender = Gender.Male,
                    FirstName = "Robert",
                    MiddleInitial = "J",
                    Surname = "Williams",
                    Address = new Address
                    {
                        StreetAddress = "4908 Ford Street",
                        City = "San Jose",
                        State = "CA",
                        ZipCode = 95134,
                        Country = "US",
                    },
                    EmailAddress = "RobertJWilliams@pookmail.com",
                    TelephoneNumber = "408-424-1230",
                    MothersMaiden = "Tibbits",
                    NextBirthday = Convert.ToDateTime("22-Aug-54"),
                    CCType = "MasterCard",
                    CaseFileID = "560-84-2584",
                    UPS = "1Z 299 738 53 3451 194 9",
                    Occupation = "Merchant marine officer",
                    Domain = "EducationExpense.com",
                    MembershipLevel = "A+",
                    Kilograms = "99.9",
                },
                new Customer
                {
                    Id = 24,
                    Gender = Gender.Male,
                    FirstName = "Joseph",
                    MiddleInitial = "H",
                    Surname = "Benson",
                    Address = new Address
                    {
                        StreetAddress = "4186 Quincy Street",
                        City = "Eagleville",
                        State = "PA",
                        ZipCode = 19403,
                        Country = "US",
                    },
                    EmailAddress = "JosephHBenson@pookmail.com",
                    TelephoneNumber = "267-476-1316",
                    MothersMaiden = "Fitzgerald",
                    NextBirthday = Convert.ToDateTime("6-May-59"),
                    CCType = "MasterCard",
                    CaseFileID = "184-03-8948",
                    UPS = "1Z 264 795 05 2747 768 6",
                    Occupation = "Assistant editor",
                    Domain = "GeekRegister.com",
                    MembershipLevel = "A+",
                    Kilograms = "101.7",
                },
                new Customer
                {
                    Id = 25,
                    Gender = Gender.Male,
                    FirstName = "Lloyd",
                    MiddleInitial = "J",
                    Surname = "Gaines",
                    Address = new Address
                    {
                        StreetAddress = "2402 Melody Lane",
                        City = "Richmond",
                        State = "VA",
                        ZipCode = 23219,
                        Country = "US",
                    },
                    EmailAddress = "LloydJGaines@dodgit.com",
                    TelephoneNumber = "804-446-4229",
                    MothersMaiden = "Ramsey",
                    NextBirthday = Convert.ToDateTime("1-Jan-61"),
                    CCType = "MasterCard",
                    CaseFileID = "224-26-6622",
                    UPS = "1Z 131 078 18 1476 684 3",
                    Occupation = "Digital electronic prepress worker",
                    Domain = "LacrosseFields.com",
                    MembershipLevel = "A+",
                    Kilograms = "69.9",
                },
                new Customer
                {
                    Id = 26,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Terrie",
                    MiddleInitial = "D",
                    Surname = "Scott",
                    Address = new Address
                    {
                        StreetAddress = "4081 Tavern Place",
                        City = "Wheeling",
                        State = "WV",
                        ZipCode = 26003,
                        Country = "US",
                    },
                    EmailAddress = "TerrieDScott@mailinator.com",
                    TelephoneNumber = "304-231-9893",
                    MothersMaiden = "Alvarado",
                    NextBirthday = Convert.ToDateTime("6-Sep-37"),
                    CCType = "MasterCard",
                    CaseFileID = "234-43-8651",
                    UPS = "1Z V79 E05 88 6362 701 1",
                    Occupation = "High school counselor",
                    Domain = "SatelliteBroadcaster.com",
                    MembershipLevel = "B+",
                    Kilograms = "99.1",
                },
                new Customer
                {
                    Id = 27,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Edith",
                    MiddleInitial = "T",
                    Surname = "Shuey",
                    Address = new Address
                    {
                        StreetAddress = "2176 Shadowmar Drive",
                        City = "Metairie",
                        State = "LA",
                        ZipCode = 70001,
                        Country = "US",
                    },
                    EmailAddress = "EdithTShuey@mailinator.com",
                    TelephoneNumber = "504-858-6559",
                    MothersMaiden = "Walker",
                    NextBirthday = Convert.ToDateTime("21-Jul-35"),
                    CCType = "Visa",
                    CaseFileID = "438-01-2012",
                    UPS = "1Z 986 047 66 1059 603 9",
                    Occupation = "Babysitter",
                    Domain = "CubicalStore.com",
                    MembershipLevel = "B+",
                    Kilograms = "56.8",
                },
                new Customer
                {
                    Id = 28,
                    Gender = Gender.Male,
                    FirstName = "Romeo",
                    MiddleInitial = "S",
                    Surname = "Bailey",
                    Address = new Address
                    {
                        StreetAddress = "2859 Archwood Avenue",
                        City = "Jackson",
                        State = "WY",
                        ZipCode = 83001,
                        Country = "US",
                    },
                    EmailAddress = "RomeoSBailey@trashymail.com",
                    TelephoneNumber = "307-733-7961",
                    MothersMaiden = "White",
                    NextBirthday = Convert.ToDateTime("15-May-32"),
                    CCType = "Visa",
                    CaseFileID = "520-51-6974",
                    UPS = "1Z 493 479 55 7168 337 5",
                    Occupation = "Placement specialist",
                    Domain = "PlatinumZoom.com",
                    MembershipLevel = "AB+",
                    Kilograms = "100.2",
                },
                new Customer
                {
                    Id = 29,
                    Gender = Gender.Male,
                    FirstName = "Albert",
                    MiddleInitial = "P",
                    Surname = "Zhao",
                    Address = new Address
                    {
                        StreetAddress = "3029 Windy Ridge Road",
                        City = "Fort Wayne",
                        State = "IN",
                        ZipCode = 46805,
                        Country = "US",
                    },
                    EmailAddress = "AlbertPZhao@trashymail.com",
                    TelephoneNumber = "260-483-4269",
                    MothersMaiden = "Lopez",
                    NextBirthday = Convert.ToDateTime("26-Nov-59"),
                    CCType = "MasterCard",
                    CaseFileID = "315-56-5381",
                    UPS = "1Z 560 718 11 5121 224 5",
                    Occupation = "Derrick operator",
                    Domain = "ReserveHouses.com",
                    MembershipLevel = "A+",
                    Kilograms = "81.2",
                },
                new Customer
                {
                    Id = 30,
                    ClubMembershipType = ClubMembershipTypes.Platinum,Gender = Gender.Female,
                    FirstName = "Dawn",
                    MiddleInitial = "M",
                    Surname = "Bly",
                    Address = new Address
                    {
                        StreetAddress = "1740 Johnny Lane",
                        City = "New Berlin",
                        State = "WI",
                        ZipCode = 53151,
                        Country = "US",
                    },
                    EmailAddress = "DawnMBly@trashymail.com",
                    TelephoneNumber = "414-232-4723",
                    MothersMaiden = "Victor",
                    NextBirthday = Convert.ToDateTime("19-Sep-75"),
                    CCType = "Visa",
                    CaseFileID = "387-34-8310",
                    UPS = "1Z 117 900 56 5937 155 1",
                    Occupation = "Industrial engineer",
                    Domain = "LuxembourgRentals.com",
                    MembershipLevel = "A+",
                    Kilograms = "66.3",
                },
            };
            foreach (Customer c in customers)
            {
                c.FullName = c.FirstName + " " + c.Surname;
            }

            return customers;
        }
    }
}

